<a href="https://colab.research.google.com/github/rajarajeswarir/Pytorch-learning/blob/main/Copy_of_00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch


# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor


tensor([[0.3786, 0.2655, 0.8536, 0.1788, 0.2301, 0.3892, 0.2153],
        [0.4946, 0.4788, 0.1241, 0.3336, 0.2080, 0.7242, 0.6136],
        [0.3690, 0.3611, 0.5834, 0.8731, 0.2197, 0.2717, 0.1714],
        [0.7802, 0.4690, 0.8375, 0.3943, 0.9244, 0.9301, 0.1010],
        [0.0895, 0.3985, 0.2940, 0.7262, 0.0121, 0.3323, 0.1210],
        [0.5273, 0.9476, 0.3067, 0.8294, 0.1628, 0.8245, 0.3559],
        [0.2105, 0.6550, 0.0423, 0.9049, 0.9020, 0.1936, 0.0761]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_1 = torch.rand(1, 7)
random_tensor @ torch.t(random_tensor_1)
# Perform matrix multiplication 


tensor([[1.1448],
        [1.3956],
        [1.3027],
        [2.3664],
        [0.7614],
        [1.6744],
        [1.5920]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed


# Create two random tensors
RANDOM_SEED = 0
torch.manual_seed(0)
random_tensor_C = torch.rand(7, 7)

torch.manual_seed(0)
random_tensor_D = torch.rand(7, 1)

#print(random_tensor_C)
#print(random_tensor_D)
#print(random_tensor_C @ random_tensor_D)
torch.matmul(random_tensor_C, random_tensor_D)
# Matrix multiply tensors


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
torch.manual_seed(1234)
tensor_A = torch.rand(2, 3)
torch.manual_seed(1234)
tensor_B = torch.rand(2, 3)
print(tensor_A, tensor_A.device) 
print(tensor_B, tensor_B.device) 

tensor_on_gpu_A = tensor_A.to(device)
tensor_on_gpu_B = tensor_B.to(device)
print(tensor_on_gpu_A, tensor_on_gpu_A.device) 
print(tensor_on_gpu_B, tensor_on_gpu_B.device) 

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
mul_gpu_result = torch.matmul(tensor_on_gpu_A, torch.t(tensor_on_gpu_A))
mul_gpu_result, mul_gpu_result.shape

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(torch.max(mul_gpu_result))
# Find min
print(torch.min(mul_gpu_result))

tensor(0.6287, device='cuda:0')
tensor(0.2161, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(mul_gpu_result.argmax())

# Find arg min
print(mul_gpu_result.argmin())

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)


# Remove single dimensions
random_tensor_1 = random_tensor.squeeze()

# Print out tensors and their shapes
print(f"Previous tensor: {random_tensor}")
print(f"Previous shape: {random_tensor.shape}")
print(f"\nNew tensor: {random_tensor_1}")
print(f"New shape: {random_tensor_1.shape}")

Previous tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Previous shape: torch.Size([1, 1, 1, 10])

New tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
New shape: torch.Size([10])
