<a href="https://colab.research.google.com/github/rajarajeswarir/Pytorch-learning/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot
print(torch.__version__)

1.13.0+cu116


## Introduction to Tensors

### Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 7],
                       [3, 6, 8]],
                       [[4, 5, 9],
                       [6, 7, 8],
                       [8, 9, 3]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 7],
         [3, 6, 8]],

        [[4, 5, 9],
         [6, 7, 8],
         [8, 9, 3]]])

In [ ]:
# TENSOR
TENSOR_1 = torch.tensor([[[[1, 2],
                       [4, 5]],
                       [[4, 5],
                       [6, 7]],
                       [[4, 5],
                       [6, 7]]],
                       [[[1, 2],
                       [4, 5]],
                       [[4, 5],
                       [6, 7]],
                       [[4, 5],
                       [6, 7]]]])
TENSOR_1

tensor([[[[1, 2],
          [4, 5]],

         [[4, 5],
          [6, 7]],

         [[4, 5],
          [6, 7]]],


        [[[1, 2],
          [4, 5]],

         [[4, 5],
          [6, 7]],

         [[4, 5],
          [6, 7]]]])

In [ ]:
print(TENSOR_1.ndim)
print(TENSOR_1.shape)


4
torch.Size([2, 3, 2, 2])


### Random tensors

In [ ]:
# Create a random tensor of shape

random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.6364, 0.4355, 0.7648, 0.4279],
        [0.3676, 0.3406, 0.5841, 0.8751],
        [0.6530, 0.5189, 0.3817, 0.7495]])


In [ ]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tensor_1 = torch.rand(size = (3, 10, 10))
print(random_tensor_1)

tensor([[[0.3373, 0.0062, 0.8270, 0.5536, 0.4309, 0.4599, 0.3424, 0.6785,
          0.2099, 0.8879],
         [0.1292, 0.1863, 0.0556, 0.9118, 0.4771, 0.5412, 0.8911, 0.9431,
          0.8914, 0.6252],
         [0.2449, 0.5660, 0.6122, 0.4702, 0.0207, 0.3425, 0.2941, 0.1214,
          0.0054, 0.6514],
         [0.1779, 0.1892, 0.7165, 0.4403, 0.4581, 0.8782, 0.5257, 0.3715,
          0.8217, 0.9995],
         [0.1371, 0.1601, 0.2057, 0.9266, 0.3572, 0.3808, 0.4618, 0.7483,
          0.5229, 0.3920],
         [0.2859, 0.1807, 0.1863, 0.4849, 0.7113, 0.4385, 0.7668, 0.9362,
          0.2176, 0.6348],
         [0.9007, 0.5716, 0.9010, 0.8601, 0.6514, 0.1768, 0.7591, 0.5342,
          0.4195, 0.2134],
         [0.8589, 0.4852, 0.2373, 0.5962, 0.8120, 0.1122, 0.9288, 0.0590,
          0.4890, 0.3206],
         [0.6545, 0.1212, 0.1497, 0.4332, 0.2399, 0.9512, 0.8161, 0.2134,
          0.8977, 0.1810],
         [0.7271, 0.2853, 0.8617, 0.9279, 0.9566, 0.3844, 0.3468, 0.4732,
          0.8592,

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros 

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = None,
                               device = None,
                               requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)

In [ ]:
int_32_tensor * float_16_tensor


tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
# Create a tensor 
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1327, 0.9371, 0.0952, 0.4359],
        [0.8580, 0.0683, 0.8078, 0.1253],
        [0.7261, 0.4867, 0.0728, 0.7388]])

In [ ]:
# Find out details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1327, 0.9371, 0.0952, 0.4359],
        [0.8580, 0.0683, 0.8078, 0.1253],
        [0.7261, 0.4867, 0.0728, 0.7388]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (Tensor operations)

Tensors operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10

In [ ]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([110, 120, 130])

In [ ]:
torch.add(tensor, 5)

tensor([16, 17, 18])

In [ ]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals: tensor([121, 144, 169])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(434)

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x.dtype

torch.int64

In [ ]:
torch.min(x), x.min(), torch.max(x), x.max()

(tensor(0), tensor(0), tensor(90), tensor(90))

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping, viewing, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim =0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([4, 9]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]), torch.Size([9, 4]))

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Removes extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specified dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (Selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
print(x[0][1][1])
print(x[0][2][2])
print(x[:, :, 1])
print(x[:, 1, 1])
print(x[0, 0, :])
print(x[0, :, 2])

tensor(5)
tensor(9)
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])
tensor([3, 6, 9])


## Pytorch tensors & Numpy

NumPy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`

* Pytorch tensor -> `torch.Tensor.numpy()`


In [ ]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified explicitly
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to 'tensor'?

array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor =  tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducilibilty (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and Pytorch comes the concept of **random seed**

Essentially what the random seed does is "flavour" the randomness

In [ ]:
torch.rand(3, 3)

tensor([[0.9569, 0.3624, 0.9914],
        [0.0342, 0.4357, 0.4903],
        [0.6992, 0.5966, 0.8457]])

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0477, 0.9611, 0.5479, 0.0044],
        [0.0127, 0.8190, 0.3677, 0.7331],
        [0.4339, 0.9433, 0.7511, 0.6444]])
tensor([[0.5217, 0.6475, 0.7285, 0.1058],
        [0.3705, 0.0127, 0.7165, 0.2587],
        [0.1294, 0.2031, 0.2952, 0.2213]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 30
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (and making faster computations)

### Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - Takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure

In [ ]:
!nvidia-smi

Fri Dec  9 03:24:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0    25W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch 

In [ ]:
import torch

torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device) 

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###4. Moving tensors back to the CPU

In [ ]:
# if tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])